### ISSUE TITLE
in dijango-cms 4.1 and fronted

### ISSUE THREAD

**Issue by olariuromeo** [django-cms/djangocms-link#221]
python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "dev/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "dev/lib/python3.11/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "dev/lib/python3.11/site-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
  File "dev/lib/python3.11/site-packages/django/contrib/admin/__init__.py", line 50, in autodiscover
    autodiscover_modules("admin", register_to=site)
  File "dev/lib/python3.11/site-packages/django/utils/module_loading.py", line 58, in autodiscover_modules
    import_module("%s.%s" % (app_config.name, module_to_search))
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "dev/lib/python3.11/site-packages/cms/admin/__init__.py", line 11, in <module>
    plugin_pool.plugin_pool.discover_plugins()
  File "dev/lib/python3.11/site-packages/cms/plugin_pool.py", line 42, in discover_plugins
    autodiscover_modules('cms_plugins')
  File "dev/lib/python3.11/site-packages/django/utils/module_loading.py", line 58, in autodiscover_modules
    import_module("%s.%s" % (app_config.name, module_to_search))
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "dev/lib/python3.11/site-packages/djangocms_link/cms_plugins.py", line 7, in <module>
    from .forms import LinkForm
  File "dev/lib/python3.11/site-packages/djangocms_link/forms.py", line 10, in <module>
    class LinkForm(ModelForm):
  File "dev/lib/python3.11/site-packages/djangocms_link/forms.py", line 11, in LinkForm
    internal_link = PageSearchField(
                    ^^^^^^^^^^^^^^^^
  File "dev/lib/python3.11/site-packages/djangocms_link/fields_select2.py", line 45, in __init__
    kwargs['queryset'] = self.widget.get_queryset()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "dev/lib/python3.11/site-packages/djangocms_link/fields_select2.py", line 32, in get_queryset
    return Page.objects.drafts()
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'PageManager' object has no attribute 'drafts'

**Comment by filipweidemann** [comment]
@fsbraun Hey Fabian, would you kindly look at https://github.com/django-cms/djangocms-link/compare/master...filipweidemann:djangocms-link:master?

I didn't want to open a PR just yet because the whole test suite also needs to be updated (`djangocms-text-ckeditor` as a reference is nice). 

My patch is kind of simple, just remove the call to `draft()` on all pages and instead return the whole queryset. If I understand this whole versioning transition correctly, this would yield the expected result since there is only one `Page` but many `PageContent`s corresponding to their own draft. So, in other words, all we need to care about for linking is the `Page` while the versioning handles the rest, aka finding the currently published draft.

Can you confirm this? If so, I'd push through and do the refactoring of the whole test suite like it was done in `djangocms-text-ckeditor`.

**Comment by fsbraun** [comment]
@filipweidemann That's the right direction. I'd go for a solution that works both with CMS 3 and CMS 4.

For example:
```
def get_queryset(self):
    if hasattr(Page.objects, "drafts"):
        # django CMS 3.x
        if self.site:
            return Page.objects.drafts().on_site(self.site)
        return Page.objects.drafts()
    # django CMS 4
    if self.site:
        return Page.objects.on_site(self.site)
    return Page.objects.all()
```

**Comment by filipweidemann** [comment]
Very clean. I'll start working on a PR next week :)

**Comment by filipweidemann** [comment]
@fsbraun here you go: https://github.com/django-cms/djangocms-link/pull/226 
Would be nice if you can find some time to either comment on any needed changes or, if everything looks fine, to actually merge this into master so I can start using it :)
